### Operations with `pytorch`

In [1]:
import torch

### Addition

In [2]:
x = torch.Tensor(5, 3)
y = torch.rand(5, 3)

In [3]:
print(x + y)

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


In [4]:
out = x + y
print(out)

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


In [5]:
# syntax 2:
print(torch.add(x, y))

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


In [6]:
out = torch.add(x, y)
print(out)

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


In [8]:
# in-place
y.add_(x)
print(y)

tensor([[ 3.0410e-01,  8.4190e-01,  3.4996e-01],
        [ 4.7828e-01,         nan,  8.7231e-01],
        [ 2.0315e+20,  2.7829e-01,  1.3088e+22],
        [ 5.2897e+22,  6.2538e-01,  7.5638e-01],
        [ 3.1520e-01,  3.3090e+21,  7.9566e-01]])


**NOTE:** Any operation that mutates a tensor in-pace is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [9]:
# You can use standard NumPy-like indexing
print(x[:, 1])

tensor([ 0.0000e+00,         nan,  1.1038e-05,  8.4639e-07,  3.3090e+21])


### Reshaping: `Tensor.view(*shape)`

In [10]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print('x.size() = {}'.format(x.size()))
print('y.size() = {}'.format(y.size()))
print('z.size() = {}'.format(z.size()))

x.size() = torch.Size([4, 4])
y.size() = torch.Size([16])
z.size() = torch.Size([2, 8])


In [11]:
# Tensor.view_as(Tensor)

a = x.view_as(z)  # inferred from a Tensor shape
print('a.size() = {}'.format(a.size()))

a.size() = torch.Size([2, 8])
