### Operations with `pytorch`

In [1]:
import torch

### Addition

In [2]:
x = torch.Tensor(5, 3)
y = torch.rand(5, 3)

print(x + y)

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


In [3]:
# Syntax 1:
out = x + y
print(out)

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


In [4]:
# Syntax 2:
print(torch.add(x, y))

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


In [5]:
out = torch.add(x, y)
print(out)

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


In [7]:
# in-place
y.add_(x)
print(y)

tensor([[ 0.7166,  0.5940,  0.0428],
        [ 0.8187,  0.8350,  0.5269],
        [ 0.3619,  0.4527,  0.6936],
        [ 0.2971,  0.8350,  0.4947],
        [ 0.1850,  0.5780,  0.1578]])


> **NOTE:** Any operation that mutates a tensor in-pace is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [8]:
# You can use standard NumPy-like indexing
print(x[:, 1])

tensor(1.00000e-39 *
       [ 0.0000,  0.0000,  0.0000,  7.6851,  0.0000])


### Reshaping: `Tensor.view(*shape)`

In [9]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions

print('x.size() = {}'.format(x.size()))
print('y.size() = {}'.format(y.size()))
print('z.size() = {}'.format(z.size()))

x.size() = torch.Size([4, 4])
y.size() = torch.Size([16])
z.size() = torch.Size([2, 8])


In [10]:
# Tensor.view_as(Tensor)

a = x.view_as(z)  # inferred from a Tensor shape
print('a.size() = {}'.format(a.size()))

a.size() = torch.Size([2, 8])


In [11]:
print(x)
print(a)

tensor([[ 0.8429,  0.8422,  0.3102,  0.4824],
        [ 0.6741,  0.3650,  0.5389,  0.6560],
        [ 0.8008,  0.1852,  0.0369,  0.3659],
        [ 0.3848,  0.6965,  0.6806,  0.8309]])
tensor([[ 0.8429,  0.8422,  0.3102,  0.4824,  0.6741,  0.3650,  0.5389,
          0.6560],
        [ 0.8008,  0.1852,  0.0369,  0.3659,  0.3848,  0.6965,  0.6806,
          0.8309]])


If you have a one element tensor, use `.item()` to get the value as a Python number.

In [12]:
x = torch.rand(1)
print('Tensor: {}'.format(x))
print('Value:  {}'.format(x.item()))

Tensor: tensor([ 0.4394])
Value:  0.4393714666366577


### NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

> The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

#### Converting a Torch Tensor to a NumPy Array

In [13]:
# a is a torch tensor.
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [14]:
# b is a numpy array.
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [15]:
# a & b share the same memory location.
# changing a will change b & vice versa.
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


#### Converting NumPy Array to Torch Tensor

> See how changing the Numpy array changed the Torch Tensor automatically. 

In [16]:
import numpy as np

In [17]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


In [18]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


> **NOTE**: All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [19]:
# Let's run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    # a CUDA device object.
    device = torch.device("cuda")
    
    # Directly create a tensor on GPU
    y = torch.ones_like(x, device=device)
    
    # or just use strings ``.to("cuda")``
    x = x.to(device)
    
    # GPU tensor operations are performed on GPU.
    z = x + y
    
    # Still on GPU.
    print(z)
    
    # Send tensor to CPU. ``.to`` can also change dtype together!
    print(z.to("cpu", torch.double))
    
else:
    print("CUDA isn't available on this device.")

CUDA isn't available on this device.
