## What is PyTorch?

It's a Python based scientific computing package targeted at two sets of audiences:
- A replacement for `numpy` to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

Tensors are similar to Numpy's `ndarray`, except Tensors are GPU accelerated meaning you tensors & it's operations can be run on GPUs to accelerate computation.

In [1]:
# Typical PyTorch import.
import torch

Construct a 5x3 matrix, uninitialized.

In [2]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-41 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0007,  1.1614],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.2152,  0.2152],
        [ 0.0000,  0.0000,  0.0000]])


Construct a randomly initialized matrix.

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.8658,  0.2227,  0.5247],
        [ 0.9260,  0.7216,  0.1650],
        [ 0.1994,  0.8871,  0.5339],
        [ 0.4535,  0.1087,  0.6472],
        [ 0.4315,  0.5413,  0.9135]])


Construct a matrix filled with `0` with data type of `long`

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data.

In [5]:
x = torch.tensor([5.5, 3.])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor basing on existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.int)       # *new_ methods take in sizes.
print(x)

# Takes in the shape of `x` but with new data types.
x = torch.rand_like(x, dtype=torch.double)  # override dtype!
print(x)                                    # result has the same size

tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]], dtype=torch.int32)
tensor([[ 0.7877,  0.4616,  0.1448],
        [ 0.1567,  0.2438,  0.4090],
        [ 0.0940,  0.4504,  0.4793],
        [ 0.6853,  0.5664,  0.4507],
        [ 0.3342,  0.9065,  0.4988]], dtype=torch.float64)


Get it's size

In [7]:
print(x.size())

torch.Size([5, 3])


Note: `torch.Size` is infact a tuple therefore, it supports all tuple's operations.