## What is PyTorch?

It's a Python based scientific computing package targeted at two sets of audiences:
- A replacement for `numpy` to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

In [1]:
import torch

In [2]:
# Construct a 5x3 matrix
x = torch.Tensor(5, 3)
print(x)


1.00000e-29 *
  0.0000  0.0000  3.9260
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [3]:
# Construct a 5x3 randomly initialized matrix
x = torch.rand(5, 3)
print(x)


 0.9152  0.4046  0.7690
 0.6653  0.6564  0.9553
 0.4627  0.0858  0.8089
 0.2361  0.9341  0.0296
 0.0496  0.9051  0.3340
[torch.FloatTensor of size 5x3]



In [4]:
# get it's size
x.size()

torch.Size([5, 3])

In [5]:
y = torch.FloatTensor(3, 5)
print(y)


 0.0000e+00  0.0000e+00  2.6258e-29  3.6893e+19  5.6052e-45
 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  2.6372e-29
[torch.FloatTensor of size 3x5]



In [6]:
# Taking a dot product of x with y using the Python 3.5 syntax
product = x@y
print(product)


 0.0000e+00  0.0000e+00  2.4032e-29  3.3767e+19  2.0280e-29
 0.0000e+00  0.0000e+00  1.7468e-29  2.4544e+19  2.5193e-29
 0.0000e+00  0.0000e+00  1.2150e-29  1.7072e+19  2.1332e-29
 0.0000e+00  0.0000e+00  6.1984e-30  8.7092e+18  7.8053e-31
 0.0000e+00  0.0000e+00  1.3022e-30  1.8297e+18  8.8081e-30
[torch.FloatTensor of size 5x5]



## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

**NOTE:** The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [7]:
import numpy as np

In [8]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [9]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value

In [10]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


In [11]:
# b is a numpy array from the torch Tensor, a
# c is a torch tensor created from the numpy array, b
# a, b & c shares the same memory location
c = torch.from_numpy(b)
print(c)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]



In [12]:
a.add_(3)
print(f'a = {a} Torch')
print(f'b = {b} Numpy')
print(f'c = {c} Torch')

a = 
 5
 5
 5
 5
 5
[torch.FloatTensor of size 5]
 Torch
b = [5. 5. 5. 5. 5.] Numpy
c = 
 5
 5
 5
 5
 5
[torch.FloatTensor of size 5]
 Torch


### Converting NumPy array to Torch Tensor

See how the change in the `np array` changed the Torch Tensor automatically

In [13]:
a = np.ones(5)
b = torch.from_numpy(a)

# Add 1 to a and store the result in a
# i.e. Update the value of a by adding 1 to it.
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



## CUDA Tensors

Tensors can be moved into the GPU using the `.cuda` method.

In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    # Create `x` as a Float tensor on the GPU
    x = torch.cuda.FloatTensor(5, 3)
    # Randomly initialize y ont the GPU
    y = torch.rand(5, 3).cuda()
    result = torch.Tensor(5, 3).cuda()
    # Add a & b on the GPU
    torch.cuda.torch.add(a, b, out=result)
    # PRINT THE RESULT
    print(x + y)
else:
    print('You dont\'t have a GPU or CUDA isn\'t enabled')

You dont't have a GPU or CUDA isn't enabled
